### ISSUE TITLE
Scalar Flow Type does not exist in imported subsystem

### ISSUE THREAD

**Issue by lelandstarr** [modelint/shlaer-mellor-metamodel#10]
https://github.com/modelint/shlaer-mellor-metamodel/blob/e96cbdb2eb04550820b3726c23f190d7fa41e0fa/action-language-metamodel/access-action-subsystem/access-action-subsystem.xmm#L89

**Comment by modelint** [comment]
I'm going to review this once I finish the Event Specification Subsystem.  Those names are going to shift around a bit as I make progress. Will announce when I feel they are reasonably stable.
