### ISSUE TITLE
Lineage solution inside the Relationship Subsystem

### ISSUE THREAD

**Issue by erik-soederholm** [modelint/shlaer-mellor-metamodel#34]
I have a number of small comment about the Lineage solution inside the Relationship Subsystem. Note that this is only opinions from my side but with a slight feeling that something is hidden (but I could be wrong). I look at the “miUML td3 Relationships Subsystem” model and noticed some changes between these two versions of the model. To begin with, the renaming of ‘Generalization Role’ to ‘Facet’ (I liked that!). Henceforth when I use ‘Facet’ I will mean the class form the new model. The change from Specialized Class to Facet in R131 is my main issue.. I try to explain: Class A could be part of multiple Generalizations at the same time and hence have multiple Facets. Given the “Lineage tracing algorithm” point of view it is only interesting if class A is in the Lineage or not. Thus, the algorithm is only valid if all Facets of class A is either in the Lineage or they are not. Currently the class model does not hinder half of the Facets from being inside a Linage. The same was not true for the miUML version of the subsystem where the Specialized Class was either in the Linage or not. Therefore, I think the solution in the miUML version was better. Finally I would like to point out that the R131 associations class name “Class In Lineage” is not corresponding perfectly with the meaning of the R131 association (which I would describe as “Facet In Lineage”).

**Comment by modelint** [comment]
First of all, glad you like the term Facet. It's difficult to come up with names that are meaningful and not too weird or too similar to other names, leading to confusion. Facet does collide with the concept we used in Models to Code where we talk about the class model, state model and action facets of the method, but keeping context clear, it shouldn't be a big problem.

In the SM metamodel, I seem to remember changing "Specialized Class" to Class In Lineage. I felt it best to just go ahead and be direct here. Though, maybe I should call it Facet in Lineage instead?

It took me a few minutes to work out your meaning and compare the miUML and SM versions sorting through all the name changes! But I sketched out an example and, yeah, I see what you mean! The younger version of myself was probably smarter (or at maybe less distracted!). I will ponder a way to fix it in the SM model.

**Comment by modelint** [comment]
I think the best approach is to revert to the older model a bit. I will subclass Class again (specialized/non-specialized). Then swap it on R101. Then replace Facet on R131 with Specialized Class.  So basically what I did before.  Will start a new branch for this and should have it done early this week. Maybe even tomorrow, schedule permitting.

**Comment by modelint** [comment]
On second glance, I realized that I can just move R131 over from Facet to Class and then lose the Rnum referential.  There is really no need to create a Specialized / Non Specialized Class generalization like I had in the miUML model. The algorithm that builds the Lineages will already be constrained so that it does not include non-specialized classes.  I have just the committed the update in version 4.7.0.
