### ISSUE TITLE
Subsystem Numbering Range Identifier

### ISSUE THREAD

**Issue by erik-soederholm** [modelint/shlaer-mellor-metamodel#35]
Class “Subsystem Numbering Range” in the Domain Subsystem:
Attributes Floor and Ceiling makes I and I2 super identifiers. The inclusion of Floor and Ceiling is not limiting the possibility for two subsystems to share the same identical Numbering Range.
I’m not entirely sure of the goal here but one way would be to remove I, I2 from the Subsystem and Domain attributes. As follows:
class Subsystem Numbering Range
attributes
    Floor : Element Number {I}
    Ceiling : Element Number {I2c}
    Subsystem {R3}
    Domain {R3}
–

**Comment by modelint** [comment]
Yeah, it is sloppy modeling and the inclusion of the Subsystem in the Identifier is a flaw.  In my defense, I just didn't want to spend much time thinking about the problem and left it as is. I think the correct solution involves:
Domain <-->> Subsystem Partition (reflexive 1c:1c greater than/less than) <-- Subsystem Numbering Range <--> Subsystem
The above solution would eliminate overlapping ranges. But it seems a bit heavy handed for such little gain.
I am inclined to keep it simple, along the lines of your solution and just specify the constraint in the description.  Will do an update.

**Comment by modelint** [comment]
OMG, I'm such an idiot. The solution is so obvious now that I put more than one brain cell on it. Will post an update shortly.

**Comment by modelint** [comment]
There. I fixed it. Version 2.4.0
