### ISSUE TITLE
This is a duplicate system name, I believe it should be "Signal Action" not Action

### ISSUE THREAD

**Issue by lelandstarr** [modelint/shlaer-mellor-metamodel#8]
https://github.com/modelint/shlaer-mellor-metamodel/blob/e96cbdb2eb04550820b3726c23f190d7fa41e0fa/action-language-metamodel/signal-action-subsystem/signal-action-subsystem.xmm#L11

**Comment by modelint** [comment]
I'm going to review this once I finish the Event Specification Subsystem.  Those names are going to shift around a bit as I make progress. Will announce when I feel they are reasonably stable.
